### ISSUE TITLE
ENV not being generated after running mre build

### ISSUE THREAD

**Issue by albanshahini** [microrealestate/microrealestate#136] opened 2023-11-03 18:21 UTC
Hey all-

Few users and I are stuck for months now installing this app using docker. This is not our first rodeo but somehow it just won't work. Here is what we are doing:

1. Cloning the git
2. cd to new folder
3. running ./mre build

After we run this, it asks us three questions, in which we answer, then immediately shows us a lot of red lines, which we think means that an env file as not generated.

The issues we're encountering:

1. The build shows at least 20 lines with errors (see screenshot)
2. If we want to re-run ./mre build, it never asks us the questions again in case we entered something incorrectly or want to change something

See attached screenshot

![micro](https://github.com/microrealestate/microrealestate/assets/11700400/0a9a8b4d-e9f4-469f-9ba1-4fdf881f057f)

**Comment by nathanaelmoyer** [comment] 2023-11-03 19:55
I am also getting a very similar issue using docker. I am running on Ubuntu 22.04.2 LTS. Here is my output if this helps:

Output after running ./mre build
![image](https://github.com/microrealestate/microrealestate/assets/36149055/b10e7a0e-d6cb-4701-8171-ee5f779e6daf)

Output after running ./mre start
![image](https://github.com/microrealestate/microrealestate/assets/36149055/82258050-6ea6-49a3-a04a-b71fefaa4c33)

**Comment by nathanaelmoyer** [comment] 2023-11-03 20:20
I also tried building the application on a Windows Server 2022 Update 21H2 VM. This produced a very similar result from the build command.

![image](https://github.com/microrealestate/microrealestate/assets/36149055/993e44d6-0dab-47fc-a048-ff22675db2ba)

**Comment by camelaissani** [comment] 2023-11-03 21:47
@nathanaelmoyer Was the .env file created in the project root folder?

**Comment by camelaissani** [comment] 2023-11-03 21:55
@albanshahini it might be caused by the urls you passed in the prompts. Could you give me a sample of what you answered? You may want to change the hostname/domain to hide your server.

**Comment by nathanaelmoyer** [comment] 2023-11-03 21:57
> @nathanaelmoyer Was the .env file created in the project root folder?


@camelaissani 
I do not see the .env file on my ubuntu system:
![image](https://github.com/microrealestate/microrealestate/assets/36149055/0ab4348d-fbb2-4a30-b035-dad9a597a7bc)


I do however see it on my windows system:
![image](https://github.com/microrealestate/microrealestate/assets/36149055/bff8b9bf-d0f4-45c4-879d-ea3de3df5922)

**Comment by camelaissani** [comment] 2023-11-03 22:17
@nathanaelmoyer could you give me a sample of the urls you put in prompts? Please change the hostname/domain to hide your server.

**Comment by nathanaelmoyer** [comment] 2023-11-03 22:33
> @nathanaelmoyer could you give me a sample of the urls you put in prompts? Please change the hostname/domain to hide your server.


I initially tried the defaults:
http://localhost:8080/landlord
http://localhost:8080/tenant

Maybe I need to replace the localhost with the device name? I'm not at my computer at the moment but I can give that a try later.

I also tried using my own domain which is similar to the following examples:
https://site.com:8080/landlord
https://site.com:8080/tenant

Not sure if https is supported but figured it was worth trying. Unfortunately, my results were the same.

**Comment by camelaissani** [comment] 2023-11-04 00:07
@nathanaelmoyer I would say no problem with your urls. I'm not sure https + port 8080 is compatible though.

I cannot reproduce this issue on my machine.

Can you try to debug the cli on your side?
Rather than running the executable you can run `node cli/src/index.js build`
Please remove the .env if it is already generated.
I'll appreciate your help.

**Comment by camelaissani** [comment] 2023-11-04 00:10
The problem might occur in this file https://github.com/microrealestate/microrealestate/blob/master/cli/src/index.js#L105

**Comment by nathanaelmoyer** [comment] 2023-11-04 00:40
> Can you try to debug the cli on your side? Rather than running the executable you can run `node cli/src/index.js build` Please remove the .env if it is already generated. I'll appreciate your help.

Happy to help!
Forgive me for I am a noob when it comes to linux still. My issue could entirely be user error and I appreciate your help diagnosing!

So here's what I found so far. I found out the .env file was in fact present. I just couldn't see it for some reason. I was able to finally see it in the gui file browser after checking the "show hidden files" option.
![image](https://github.com/microrealestate/microrealestate/assets/36149055/714c3e20-cf72-4e72-9e0f-4f9d24fe23c3)

Given the above my results have not changed from building. I thought maybe I didn't have permission to run docker properly which I have resolved but this didn't help the original error. Per your suggestion above I deleted the .env file and ran the command while in the microrealestate folder. Below is my output from that command. I hope this helps:
![image](https://github.com/microrealestate/microrealestate/assets/36149055/5c3bbc52-7736-4475-9b09-c3380554e23b)



> @nathanaelmoyer I would say no problem with your urls. I'm not sure https + port 8080 is compatible though.

Good point. I had a brain fart there. No way https would work over 8080. Thanks for pointing that out.

**Comment by camelaissani** [comment] 2023-11-04 01:31
@nathanaelmoyer sorry I forgot to mention that you need to have node 18 installed to run the JS file.
The syntax error is most likely caused by an old version of node.

**Comment by nathanaelmoyer** [comment] 2023-11-04 02:24
> @nathanaelmoyer sorry I forgot to mention that you need to have node 18 installed to run the JS file. The syntax error is most likely caused by an old version of node.

No worries! I feel like I'm so close. I was able to update to node version 18.17.1
![image](https://github.com/microrealestate/microrealestate/assets/36149055/e93577ef-2134-4587-9f8b-b216b96b9325)

For some reason though I'm still getting the same errors when building. I ran the same test with the `node cli/src/index.js build` command but am getting a new error:
![image](https://github.com/microrealestate/microrealestate/assets/36149055/9146b42e-cd93-41ae-8c41-2641e75136d6)

**Comment by Tonelock2021** [comment] 2023-11-05 22:28
I have almost what appears to be an identical issue.  I have a semi working install where the landlord web seems to be fine but the tenant web does not work. I installed it 2 weeks ago. I am using Proxmox with a debian 12 container.
I decided to roll up a new server again using Debian 12.  and cloning the git as I did before on my (semi) working system.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
After $ ./mre build
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
red errors
time="2023-11-04T23:58:35Z" level=warning msg="The \"LANDLORD_FRONTEND_PORT\" variable is not set. Defaulting to a blank string."
time="2023-11-04T23:58:35Z" level=warning msg="The \"DOCKER_GATEWAY_URL\" variable is not set. Defaulting to a blank string."
time="2023-11-04T23:58:35Z" level=warning msg="The \"APP_NAME\" variable is not set. Defaulting to a blank string."
time="2023-11-04T23:58:35Z" level=warning msg="The \"SIGNUP\" 
this goes on for a bit
the last line
failed to solve: process "/bin/sh -c yarn workspaces focus @microrealestate/landlord &&     yarn workspace @microrealestate/landlord run build" did not complete successfully: exit code: 137

I have tried  # ./mre build  as well a $ ./mre build  It always creates the .env file that appears to be correct.

I installed nodejs ver 18.13 and ran node cli/src/index.js  it errored 
![image](https://github.com/microrealestate/microrealestate/assets/86329144/eedecca6-aaeb-4fe2-9d40-bb90faeb7720)

I am pretty old school so I have not paid much attention to docker, nodejs, npm and noSQL databases. I was hoping to concentrate on the web gui side of things, but I "think" this may be related to `NODE_ENV=production`  ?
or moving the Chalk package to dependencies ?

**Comment by eriktovarj** [comment] 2023-11-07 00:58
i tried with sudo and i didnt get any errors, but got stuck in BUILDNG CONTAINERS...

**Comment by camelaissani** [comment] 2023-11-07 02:18
@nathanaelmoyer @Tonelock2021 before running the cli you have to install the dependencies listed in the` cli/package.json` file.
Here is the procedure in 3 steps to install them and run the cli

Prerequisite: having node 18 installed

**1. install yarn (a node package manager) by running this command:**
```shell
corepack enable
```
followed by this command:
```shell
corepack prepare yarn@3.3.0 --activate
```

At this step yarn should be installed. You can check by running this:
```shell
yarn --version
```
It should return
```shell
3.3.0
```

**2. install the dependencies of the mre project**
At the root of the project run this:
```shell
yarn
```
It should print this line once it is done
```shell
Done with warnings in ...
``` 

**3. run the cli with node**
```shell
node cli/src/index.js build
```

**Comment by camelaissani** [comment] 2023-11-07 02:32
@eriktovarj actually the root permissions are required to run docker compose, except if you have installed docker in rootless mode. In case you need some details you can have a look at this article https://linuxhandbook.com/rootless-docker.

BTW, building the containers can take some time.
You can try to run the application in dev mode to have more logs during the build (./mre dev).

**Comment by eriktovarj** [comment] 2023-11-07 21:47
> @eriktovarj actually the root permissions are required to run docker compose, except if you have installed docker in rootless mode. In case you need some details you can have a look at this article https://linuxhandbook.com/rootless-docker.
> 
> BTW, building the containers can take some time. You can try to run the application in dev mode to have more logs during the build (./mre dev).

i followed the instructions, same result
ubuntu 22.04
node 18.17.1
docker compose version 2.23.0
docker version 24.0.7
yarn 3.3.0
ERROR:
yarn workspace @microrealestate/tenant run build" did not complete successfully: exit code: 1

**Comment by eriktovarj** [comment] 2023-11-07 22:21
i ran the command:
./mre start

and IT WORKED
No errors when starting the app

So the errors show only in the builld process

**Comment by Tonelock2021** [comment] 2023-11-08 22:55
I did get my setup running, 

Not sure exactly what worked. I speculate that it may have had to do with installing nodejs via apt install versus following Nodejs Git install. 
I also had not allocated enough storage nor ram to my Debian virtual machine, as well the ./mre build container generation takes upwards of 10 minutes in the configuration I have. I do intend to create and reinstall in order to be more comfortable with this and to document it better as time allows.

**Comment by camelaissani** [comment] 2023-11-10 09:49
As it is difficult to troubleshoot this kind of issues, the mre executable will be modified to print more logs during the build.

Also, the problems might come from the small size of the VM where the app is built and run. I've started to optimize the Dockerfiles to get the smallest containers as possible.

Finally I will define what are the recommended machine specs for MRE

**Comment by Tonelock2021** [comment] 2023-11-11 23:17
For  what it is worth just an update on my installs and the woes I had.
They came down to space, patience and privilege. 
I did note that I needed at least 24 GB of HD space as the ` /var/lib/docker/overlay2` folder was 19GB.

I created a new LXC/vm today and allocated it 4 cpus, 8GB ram, 30gb on an ssd drive and used `sudo ./mre build`. 
This build worked but it did pin the CPU's a few times, not a great deal of ram was used 2GB at most. The disk IO was huge and the disk usage grew from about 4 gb  to 10 gb it took about 5 minutes.  I started with `sudo ./mre start` .
it all seems to be working the  '/var/lib/docker/overlay2' file is 14GB a lot smaller due to recent optimization?

Using sudo on the ./mre build and start commands releaved the errors. I did not want to bother to install docker as rootless. I think my original HD space allocation was 8 gb which of course was to small,  The largest problem was the Container build took over 15 minutes with no real feed back to the console. after actually watching the resources and disk IO a bit more closely I realized I should build it on an SSD and it took a bit over 4 minutes. 

Now I hope to actually try to use the app.

**Comment by camelaissani** [comment] 2023-11-11 23:51
@Tonelock2021 Thank you for sharing your valuable experience. It helps me a lot to improve the app.
Indeed I have already delivered some optims on the Dockerfiles. I am still improving them to have the smallest containers as possible (multi stage build, yarn cache for node modules)
I hope I will be able to push these changes by the end of the weekend.

**Comment by camelaissani** [comment] 2023-11-13 18:36
I just committed some changes. The last version might help to run the app or at least display more logs when something gets wrong.

**Comment by bhaktatejas922** [comment] 2024-01-05 01:04
also having this issue, ubuntu 20, x86, no storage limit, 4gb ram

**Comment by camelaissani** [comment] 2024-01-06 18:55
@albanshahini  @nathanaelmoyer @Tonelock2021 @eriktovarj Please follow the new installation procedure https://github.com/microrealestate/microrealestate#1-install-the-application 
No need to build the app anymore just dowload some files and run the app.

**Closed** 2024-01-19 21:29 UTC
Labels: bug
