### ISSUE TITLE
Having issues sending emails not working

### ISSUE THREAD

**Issue by adrianmartinezverax** [microrealestate/microrealestate#41] opened 2021-11-17 23:40 UTC
Having issues sending emails not working

**Comment by camelaissani** [comment] 2021-11-18 00:10
Do you have any logs? How do you run the application?

**Comment by adrianmartinezverax** [comment] 2021-11-18 00:13
I’m running the appliance on production on Ubuntu 20.04  LTS

**Comment by adrianmartinezverax** [comment] 2021-11-18 00:18
## emailer
ALLOW_SENDING_EMAILS=true
EMAILER_PORT=8400
MAILGUN_API_KEY=private_api_key
MAILGUN_DOMAIN=mg.mydomain.com
EMAIL_FROM=adrian@mg.mydomain.com
EMAIL_REPLY_TO=customer-service@mg.mydomain.com
EMAIL_BCC=manager1@mg.mydomain.com,manager2@mg.mydomain.com
EMAILER_URL=http://emailer:${EMAILER_PORT}/emailer

is there anything I am missing?

**Comment by camelaissani** [comment] 2021-11-18 00:21
The config looks like ok.
I would say the issue is similar to what was reported in #40

**Comment by camelaissani** [comment] 2021-11-20 19:56
Close this one follow up in #40

**Closed** 2021-11-20 19:57 UTC

**Comment by adrianmartinezverax** [comment] 2021-11-22 20:35
It's working properly now without any issues with the new repository. Thank you so much. But one thing why is is show an older date when I am sending first notice while the Lease start date and entry date is 22 November 2021. but when I send first notice is show "was expected to be paid on November 11, 2021." why saying an older date?

**Comment by adrianmartinezverax** [comment] 2021-11-22 21:27
and when putting expenses in tenant page its not updating still showing  "€0" but the rest works fine

**Comment by camelaissani** [comment] 2021-11-22 23:38
@adrianmartinezverax the 2 other issues should be fixed in my last commit

**Comment by adrianmartinezverax** [comment] 2021-11-23 01:23
Thank you, I have checked it. Everything is working very perfect but except 2 things like, "The billing page doesn't allow to save when the The organization/landlord belongs to a Person Account. the billing page details only able to save when it belongs to A business or an institution. And the other thing the on the invoice its showing an older date which is 1 November and Paris in the beginning of it. here is the screenshot below
<img width="1081" alt="Screen Shot 2021-11-23 at 3 19 45 AM" src="https://user-images.githubusercontent.com/45777622/142958411-cbbccaf0-c4a8-415f-99f9-334bd0fbe1b3.png">

**Comment by adrianmartinezverax** [comment] 2021-11-23 01:26
and what is supposed to where there is "Paris, November 1, 2021" (at the right hand side above "RENT CALL")

**Comment by camelaissani** [comment] 2021-11-25 23:06
"Paris, November 1, 2021" the city comes from the address you defined for the landlord.

You mention a billing page which cannot be saved, could you create another issue and attach a screenshot please?
