### ISSUE TITLE
Sending emails somtimes failed-ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by mdy405** [microrealestate/microrealestate#134] opened 2023-10-27 14:25 UTC
Sending notice sometimes failed in production. 

error:  message=The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null, stack=TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null
    at new NodeError (node:internal/errors:405:5)
    at Decipheriv.update (node:internal/crypto/cipher:182:11)
    at Object.decrypt (/usr/app/services/common/utils/crypto.js:25:14)
    at Object.sendEmail (/usr/app/services/emailer/src/emailengine.js:71:29)
    at /usr/app/services/emailer/src/emailer.js:168:36
    at Array.map (<anonymous>)
    at Object.send (/usr/app/services/emailer/src/emailer.js:148:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _send (/usr/app/services/emailer/src/routes.js:29:21), toString=value() {
          return `${this.name} [${key}]: ${this.message}`;
        }, code=ERR_INVALID_ARG_TYPE

**Comment by camelaissani** [comment] 2023-11-03 22:28
It looks like that sometimes the gmail app password fetched from db is null. Do you have any errors before this stack? Can you describe the steps to reproduce please?

**Comment by camelaissani** [comment] 2023-11-15 00:59
@mdy405 this issue might be fixed by this #139.
Could you update your app and check if it is still reproducible please?

**Closed** 2024-01-19 21:31 UTC
Labels: bug
